### ISSUE TITLE
Javascript error, keeps throwing every second.

### ISSUE THREAD

**Issue by AndreFabris** [kiswa/TaskBoard#437]
Any ideas how to solve this error?

TypeError: Cannot read property '0' of undefined
    at Scope.$scope.setColor (http://appsforce.back/myboard/js/controllers/boardsItemView.js:49:58)
    at Array.$parseFunctionCall (http://appsforce.back/myboard/lib/angular.js:12404:18)
    at $parseObjectLiteral (http://appsforce.back/myboard/lib/angular.js:12468:38)
    at Object.regularInterceptedExpression (http://appsforce.back/myboard/lib/angular.js:12910:21)
    at Scope.$digest (http://appsforce.back/myboard/lib/angular.js:14300:40)
    at Scope.$apply (http://appsforce.back/myboard/lib/angular.js:14571:24)
    at done (http://appsforce.back/myboard/lib/angular.js:9698:47)
    at completeRequest (http://appsforce.back/myboard/lib/angular.js:9888:7)
    at XMLHttpRequest.requestLoaded (http://appsforce.back/myboard/lib/angular.js:9829:9) (11:21:42:094 | error, null)

  at http://appsforce.back/myboard/lib/angular.js:11655

**Comment by AndreFabris** [comment]
@kiswa What input do you need

**Comment by kiswa** [comment]
That tag was to see if anyone else had ideas on this.

My only guess is that the build wasn't run, or didn't complete correctly.

**Comment by c0nfus3d** [comment]
I was having this issue as well after following the instructions at https://taskboard.matthewross.me/docs/intro.html

So since I had a `libs.min.js` and `app.min.js` file (like the demo board), I just copied and pasted the code from the demo board javascript files https://taskboard.matthewross.me/demo/lib/libs.min.js and https://taskboard.matthewross.me/demo/js/app.min.js into my local files and the problem was resolved.

**Comment by c0nfus3d** [comment]
Well, I do still see the error when trying to save and edit tasks.. but no longer every second. hmmm

**Comment by sheldoncoupeheure** [comment]
These errors still appear in the latest version of TaskBoard
